[version]

#network
retrofitVersion = "2.9.0"

#DI
daggerVersion = "2.44.2"

#storage
roomVersion = "2.5.0"

#android
coroutinesVersion = "1.6.4"

[libraries]

#network
retrofitCore = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }

#DI
daggerCore = { module = "com.google.dagger:dagger", version.ref = "daggerVersion" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerVersion" }

#storage
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

#android
coroutinesVersion = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion"}

[bundles]

[plugins]

